title: Learning Eco-Driving Strategies at Signalized Intersections
description: Vindula Jayawardana (MIT) and Cathy Wu (MIT)
logo: /images/intro.png
show_downloads: true
google_analytics: G-YJBFFBG3S7
theme: jekyll-theme-minimal
plugins: {jekyll-remote-theme}
